language: cpp
sudo: required
compiler:
  - clang
  - gcc
install:
  # CppUTest install
  - git clone https://github.com/cpputest/cpputest.git
  - cd cpputest
  - autoreconf -i && ./configure --prefix=/usr/local
  - make && sudo make install
  - cd ../
script: make && sudo make test
