language: c
sudo: required
compiler:
  - clang
  - gcc
install:
  # CppUTest install
  - git clone https://github.com/cpputest/cpputest.git
  - cd cpputest
  - autoreconf -i
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
script: make && sudo make test
