language: cpp
sudo: false
compiler:
  - clang
  - gcc
install:
  # clang for clang++
  - sudo apt-get install clang-3.5
  # CppUTest install
  - git clone https://github.com/cpputest/cpputest.git
  - cd cpputest
  - autoreconf -i && ./configure --prefix=/usr/local
  - make && sudo make install
  - cd ../
script: make && sudo make test
